import { FormEvent, useState } from "react";
import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { ArrowRight, Smartphone, Users } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { QuizStageMark } from "@/components/quizstage-shell";
import { supabase } from "@/integrations/supabase/client";

export const Route = createFileRoute("/join")({ head: () => ({ meta: [{ title: "Join a live room — QuizStage" }, { name: "description", content: "Join a QuizStage live quiz from your phone with a room code." }, { property: "og:title", content: "Join a live room — QuizStage" }, { property: "og:description", content: "Enter a room code and play along." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: JoinPage });

function JoinPage() { const navigate = useNavigate(); const [code, setCode] = useState(""); const [name, setName] = useState(""); const [busy, setBusy] = useState(false); async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); try { const normalized = code.trim().toUpperCase(); const { data: room, error: roomError } = await supabase.from("rooms").select("id,room_code,status").eq("room_code", normalized).maybeSingle(); if (roomError) throw roomError; if (!room || !["waiting", "presenting"].includes(room.status)) throw new Error("That room is not open right now."); const { data: participant, error } = await supabase.from("participants").insert({ room_id: room.id, display_name: name.trim() }).select("id").single(); if (error || !participant) throw error ?? new Error("Could not join this room."); sessionStorage.setItem(`quizstage-participant-${room.room_code}`, participant.id); void navigate({ to: "/live/$roomCode", params: { roomCode: room.room_code } }); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not join that room."); } finally { setBusy(false); } } return <main className="min-h-screen bg-ink text-paper"><div className="mx-auto flex min-h-screen max-w-xl flex-col px-5 py-7 sm:px-8"><QuizStageMark /><div className="my-auto py-20"><div className="mb-8 flex h-14 w-14 items-center justify-center bg-brand text-brand-foreground"><Smartphone /></div><p className="text-xs font-bold uppercase tracking-[0.18em] text-brand">Player entry</p><h1 className="mt-4 font-display text-6xl font-black uppercase leading-[0.88]">Find your<br /><span className="text-brand">room.</span></h1><p className="mt-6 max-w-sm text-paper/60">Enter the six-character code on the big screen, then choose the name your team will see.</p><form onSubmit={submit} className="mt-10 space-y-5"><label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-[0.12em] text-paper/60">Room code</span><Input className="h-16 border-paper/20 bg-paper/10 font-mono text-3xl uppercase tracking-[0.3em] text-paper placeholder:text-paper/25" value={code} onChange={(event) => setCode(event.target.value.replace(/[^a-zA-Z0-9]/g, "").slice(0, 6))} required minLength={6} maxLength={6} placeholder="QZ7K2M" /></label><label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-[0.12em] text-paper/60">Your name</span><Input className="h-14 border-paper/20 bg-paper/10 text-paper placeholder:text-paper/30" value={name} onChange={(event) => setName(event.target.value.slice(0, 40))} required placeholder="e.g. Alex" /></label><Button className="h-14 w-full" size="lg" disabled={busy}><Users /> {busy ? "Joining" : "Join the room"} <ArrowRight /></Button></form></div><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-paper/30">No app download · Works in your browser</p></div></main>; }